### ISSUE TITLE
刚用了一下这个，发现有个问题，小数点后的位数也会分割，详见看图

### ISSUE THREAD

**Issue by super456** [XmanLin/MyUtils#1]
https://github.com/XmanLin/MyUtils/blob/71090ff90fdcc12e0e22ef75f37bf4a7ecf0fe12/util/util.js#L10

如图：
![WX20200317-095938](https://user-images.githubusercontent.com/22334247/76814567-10f16680-6836-11ea-84e2-26d1d6f581fb.png)

**Comment by XmanLin** [comment]
是会有这种情况，但是因为考虑的是金钱格式化，一般来说RMB位数也就精确到分后面，也就是小数点两位

**Comment by XmanLin** [comment]
> https://github.com/XmanLin/MyUtils/blob/71090ff90fdcc12e0e22ef75f37bf4a7ecf0fe12/util/util.js#L10
> 
> 如图：
> ![WX20200317-095938](https://user-images.githubusercontent.com/22334247/76814567-10f16680-6836-11ea-84e2-26d1d6f581fb.png)

是会有这种情况，但是因为考虑的是金钱格式化，一般来说RMB位数也就精确到分后面，也就是小数点两位
